# General Jekyll Config
pygments: true
url: http://tpolecat.github.io/
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
markdown: redcarpet

# kramdown:
#   input: GFM

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#336633'
  # highlight_color: '#3498db'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: tpolecat
    twitter: tpolecat

  # "Hi, I'm _______"
  name: tpolecat
  email: rob_norris@mac.com
  tagline: "unworthy of a tagline"

  # Google Analytics key, leave blank to ignore
  # google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  # show_disclaimer: true
